export enum Prefecture {
  Hokkaido = "Hokkaido",
  Aomori = "Aomori",
  Iwate = "Iwate",
  Miyagi = "Miyagi",
  Akita = "Akita",
  Yamagata = "Yamagata",
  Hukushima = "Hukushima",
  Ibaraki = "Ibaraki",
  Tochigi = "Tochigi",
  Gunma = "Gunma",
  Saitama = "Saitama",
  Chiba = "Chiba",
  Tokyo = "Tokyo",
  Kanagawa = "Kanagawa",
  Niigata = "Niigata",
  Toyama = "Toyama",
  Ishikawa = "Ishikawa",
  Hukui = "Hukui",
  Yamanashi = "Yamanashi",
  Nagano = "Nagano",
  Gihu = "Gihu",
  Shizuoka = "Shizuoka",
  Aichi = "Aichi",
  Mie = "Mie",
  Shiga = "Shiga",
  Kyoto = "Kyoto",
  Osaka = "Osaka",
  Hyogo = "Hyogo",
  Nara = "Nara",
  Wakayama = "Wakayama",
  Tottori = "Tottori",
  Shimane = "Shimane",
  Okayama = "Okayama",
  Hiroshima = "Hiroshima",
  Yamaguchi = "Yamaguchi",
  Tokushima = "Tokushima",
  Kagawa = "Kagawa",
  Ehime = "Ehime",
  Kochi = "Kochi",
  Hukuoka = "Hukuoka",
  Saga = "Saga",
  Nagasaki = "Nagasaki",
  Kumamoto = "Kumamoto",
  Oita = "Oita",
  Miyazaki = "Miyazaki",
  Kagoshima = "Kagoshima",
  Okinawa = "Okinawa",
}

export const getPrefectureName = (prefecture: Prefecture) =>
  ({
    [Prefecture.Hokkaido]: "北海道",
    [Prefecture.Aomori]: "青森県",
    [Prefecture.Iwate]: "岩手県",
    [Prefecture.Miyagi]: "宮城県",
    [Prefecture.Akita]: "秋田県",
    [Prefecture.Yamagata]: "山形県",
    [Prefecture.Hukushima]: "福島県",
    [Prefecture.Ibaraki]: "茨城県",
    [Prefecture.Tochigi]: "栃木県",
    [Prefecture.Gunma]: "群馬県",
    [Prefecture.Saitama]: "埼玉県",
    [Prefecture.Chiba]: "千葉県",
    [Prefecture.Tokyo]: "東京都",
    [Prefecture.Kanagawa]: "神奈川県",
    [Prefecture.Niigata]: "新潟県",
    [Prefecture.Toyama]: "富山県",
    [Prefecture.Ishikawa]: "石川県",
    [Prefecture.Hukui]: "福井県",
    [Prefecture.Yamanashi]: "山梨県",
    [Prefecture.Nagano]: "長野県",
    [Prefecture.Gihu]: "岐阜県",
    [Prefecture.Shizuoka]: "静岡県",
    [Prefecture.Aichi]: "愛知県",
    [Prefecture.Mie]: "三重県",
    [Prefecture.Shiga]: "滋賀県",
    [Prefecture.Kyoto]: "京都府",
    [Prefecture.Osaka]: "大阪府",
    [Prefecture.Hyogo]: "兵庫県",
    [Prefecture.Nara]: "奈良県",
    [Prefecture.Wakayama]: "和歌山県",
    [Prefecture.Tottori]: "鳥取県",
    [Prefecture.Shimane]: "島根県",
    [Prefecture.Okayama]: "岡山県",
    [Prefecture.Hiroshima]: "広島県",
    [Prefecture.Yamaguchi]: "山口県",
    [Prefecture.Tokushima]: "徳島県",
    [Prefecture.Kagawa]: "香川県",
    [Prefecture.Ehime]: "愛媛県",
    [Prefecture.Kochi]: "高知県",
    [Prefecture.Hukuoka]: "福岡県",
    [Prefecture.Saga]: "佐賀県",
    [Prefecture.Nagasaki]: "長崎県",
    [Prefecture.Kumamoto]: "熊本県",
    [Prefecture.Oita]: "大分県",
    [Prefecture.Miyazaki]: "宮城県",
    [Prefecture.Kagoshima]: "鹿児島県",
    [Prefecture.Okinawa]: "沖縄県",
  }[prefecture]);
